### ISSUE TITLE
Rename hypha renames git repo instead

### ISSUE THREAD

**Issue by iacore** [bouncepaw/mycorrhiza#220]
```
mkdir www.aaa
cd www.aaa
git init
git commit --allow-empty -m "hi"
git branch wiki
git worktree add wiki.git wiki
mycorrhiza .
```

Now, in Mycorrhiza (Web UI),

- create wiki page `aaa`
- rename `aaa` to `bbb`

You will see that the directory `www.aaa` has changed to `www.bbb`.

**Comment by ORYLY** [comment]
To clarify, will the planned solution for the filepath problem also fix the genealogy feature documented in https://mycorrhiza.wiki/help/en/hypha#Genealogy , which seems dependent on filepaths to model subhypha and superhypha relationships ?

For example, when following the `Fruit/Apple` example from the help page, I get the following directory structure:

```
# ls -R1 wiki.git/
wiki.git/:
fruit
fruit.myco

wiki.git/fruit:
apple.myco
```

But after restarting the server (or reindexing), the genealogy relationship is gone completely:
  * The subhypha is named "fruitapple" (and displayed as "Fruitapple").
  * The hypha must be accessed through `http://127.0.0.1:$PORT/hypha/fruitapple` instead of `http://127.0.0.1:$PORT/hypha/fruit/apple`

**Comment by bouncepaw** [comment]
> The subhypha is named "fruitapple" (and displayed as "Fruitapple").

What? How does that happen? Please tell me everything

**Comment by ORYLY** [comment]
Sorry! I'm guessing my problem is with Windows paths if it's working for everyone else but me.

I compile and run mycorrhiza through MSYS2 (still using Windows go toolchain), and I suppose backslash path separators are getting into the program somewhere. I'll log a new issue after checking on a Linux distro and WSL.

**Comment by ORYLY** [comment]
Yup, running a pure Windows executable was the problem. Genealogy and subdirectories work just fine when running mycorrhiza in a Linuxy environment.
