### ISSUE TITLE
wiki path in config.ini

### ISSUE THREAD

**Issue by DanInSpace104** [bouncepaw/mycorrhiza#56]
I believe it would be useful to set path to wiki folder in config.ini file. So it would be easyer to switch wiki. And provide more consistent user expirience

**Comment by bouncepaw** [comment]
One day.

----

Perhaps, we don't need path configuration at all! What if all of the wiki stuff was in one directory?:

```
cool-wiki/
|- cool-wiki-git/ # Git repository
|- config.ini
|- registered-users.json
|- fixed-users.json
|- cache/
   |- tokens.json
   |- rendered-hyphae/
   |- resized-media/
```

And you just `cd cool-wiki` and `mycorrhiza`. All paths are standard, no configuration is needed for them.

Just an idea.

**Comment by handlerug** [comment]
@bouncepaw да

**Comment by handlerug** [comment]
I'm suggesting to decide on this feature right now, because that would make #55 a bit more straightforward and easier for end users. Actually, it'll make a whole lot of things much simpler and more convenient.

Also makes sense to name the Git folder `wiki-git` or something like that (`wiki.git` would be consistent with `wiki.db` and other possible storage names), because otherwise we'd have to either add the path into `config.ini` or consult the parent `cool-wiki` folder.

**Comment by bouncepaw** [comment]
I'll open a new issue on the folder structure. If decide to have one, there will be no need for wiki path in config.ini
